const ACTION_TYPES = {
  UPDATE_JSON_PATH_QUERY: "UPDATE_JSON_PATH_QUERY",
  FILTER_JSON_DATA: "FILTER_JSON_DATA",
  SAVE_FILE_DATA: "SAVE_FILE_DATA",
  START_FILE_READ: "START_FILE_READ",
  STOP_FILE_READ: "STOP_FILE_READ",
  RESET_DATA: "RESET_DATA",
};

export default ACTION_TYPES;
